const GamesLists = [
  {
    id: 1,
    name: "overdrive",
    imgSrc:
      "https://firebasestorage.googleapis.com/v0/b/technovision-48d0a.appspot.com/o/overdrive.jpg?alt=media&token=02237f69-0495-4950-8685-ca2b2a7c4fb7",
    heading: "OVERDRIVE",
    para: "Design a robot either wired or wireless within the specified dimensions that can operated manually and can travel through all turns of the track. The robot that will complete the specified task in least time will be the winner. Think your robot can overcome any obstacle-big or small in the least of time.",
    rules: [
      "ROBOT SPECIFICATIONS:",
      "1) The maximum dimension of the robot can be 25 cm x 20cm x15 cm (l x b x h).",
      "2) The robot may be wired or wireless.",
      "3) The length of the wire (for wired bots) should be long enough to cover the whole track and wire should remain slack during the complete run.",
      "GENERAL RULES:",
      "1) This is racing event so fastest and most balanced robot will win.",
      "2) Robot should be as per the given specifications.",
      "3) Each team can have maximum four members. Students from different institutes can form a team.",
      "4) Each member of the team must contain the identity card of his/her respected institute.",
      "5) The robot should not damage the arena.",
      "6) No test practice will be allowed on the arena.",
      "7) The robot must not leave behind any of its parts during the run; else it will result in disqualification.",
      "8) Unethical behaviour could lead to disqualification. Faculty co-ordinators have all the rights to take final decision for any matter during the event.",
      "9) Judge's decision will be considered final.",
      "10) Certificates of Participation will be given to all the teams that will participate in the event, but not to the teams which get disqualified due to disobeying any of the competition rules. *Co–ordination committee reserves the right to add or update any rule.",
      "TRACK SPECIFICATION:",
      "1) The track surface and course line may have unevenness.",
      "2) There will be certain obstacles in the race track which will try to slow down the robo.",
      "3) The design and size of the track may vary from that shown in the pictures.",
      "4) Arena will consist of Switch Bridge, speed breakers, marble pit, slippery path, rotating ting disc, curve ramp down, seesaw etc.",
      "GAME RULE:",
      "1) The competition is based on time trail system. There will a qualifying round for each team.",
      "2) The top team from qualifying round makes it to the final round on basis of time trials.",
      "3) Wires should remain slack during the course of the run. Pulling the wire to aid the robot in traversing may lead to disqualification.",
      "4) If any of the robots starts off before start up call, the counter would be restarted and the machines will get a second chance. If repeated again then team will be disqualified.",
      "5) Your robot must be ready when call is made for your team.",
      "6) Team members will be allowed only three times to touch or reset their robots position during the run. However, this will lead to a time penalty and timer will not stop during this course of action.",
      "7) The robot will be judged on basis of (in priority) :- a. Time to complete the track. b. Number of checkpoints cleared.",
      "8) Machine must not contain any readymade kits, pneumatic &hydraulic systems, IC engines.",
      "9) Decision about your robot will be taken by the organizers.",
      "10) No team will get a second chance after completing the track with poor score.",
      "FACULTY CO-ORDINATOR :- NAND JEE KANU SIR",
      "STUDENT CO-ORDINATOR :-  SOMESH TERKAR (MO. NO:- 7057179929)",
    ],
    regFee: "₹200/-",
    amount: "Rs. 200/-",
    // paymentLink: "https://rzp.io/l/Karma-PUBG",
    redirectLink: "/events/mechanical/overdrive",
  },
  {
    id: 2,
    name: "boxcricket",
    imgSrc:
      "https://firebasestorage.googleapis.com/v0/b/technovision-48d0a.appspot.com/o/box%20cricket.jpg?alt=media&token=1d140d9d-b60b-4324-b041-099a9ee1226d",
    heading: "BOX CRICKET",
    para: "",
    rules: [
      "1. Match format: 5 overs, 6 players a side (2 extra players per team)",
      "2. Over per bowler limit: only 1 bowler can bowl max 2 Overs, rest get to bowl only 1 over.",
      "3.Admin Rules:",
      "A.	All players must report at venue 30 minutes before game start.",
      "B.	If the full team doesn’t report 10 minutes prior to the official start time, the opposite team will be awarded as winners.",
      "C.	Games will be postponed in case of rain.",
      "D.	Umpire decisions are final & irrevocable.",
      "E.	Matches will be played with hard tennis ball; players are requested to come in sportswear. Spiked shoes are not allowed inside the playing area.",
      "F.	All players are expected to be courteous to each other and with the officials",
      "G.	Arguments with umpire will lead to player/team disqualification. This will be strictly followed.",
      "ENTRY FEES – 500 RS (per team)",
      "PRIZE – 1ST 3000 RS & TROPHY",
      "2ND 2000 RS & TROPHY",
    ],
    regFee: "₹500/-",
    amount: "Rs. 500/-",
    // paymentLink: "https://rzp.io/l/Karma-Ludo",
    redirectLink: "/events/mechanical/boxcricket",
  },
  {
    id: 3,
    name: "cadholic",
    imgSrc:
      "https://firebasestorage.googleapis.com/v0/b/technovision-48d0a.appspot.com/o/cadholic.jpg?alt=media&token=eeef4323-ba79-48dc-aeaf-3725e2ce653c",
    heading: "CADHOLIC",
    para: `There will be two rounds where participant’s graphics knowledge and skills in cero will be tested. You will get your prize according to your points which are out of 50.
    In our lab only cero is provided of design. 
    You may carry your laptop for design the drawing. any software you can use.`,
    rules: [
      "Round 1: Elimination Round",
      "• A 2D sketch will be given to each participants. All the participants which complete the orthographic view by using given 2D drawing in given time will be selected for final round. Time is 20 minutes for elimination round easy drawing will be given.",

      "Round 2: Final round",
      "• Any machine part will be given to the finalist. They will have to draw 3D. Time given will be 30 minutes",
      "Round 1 and 2:  scoring pattern is as follows:",
      "Design: 10 points",
      "Dimensioning: 10 points",
      "Line types: 10 points",
      "Symbols: 10 points",
      "Time: 10 points",
      "Entry fees – ₹100",
      "Prize:-",
      "1st Prize - 5000",
      "2nd Prize - 3000",
      "FACULTY CO-ORDINATOR: - Surajkumar Khapare Sir",
      "STUDENT CO-ORDINATOR: -  Atharva Ugale (MO NO:- 8668993637)",
    ],
    regFee: "₹100/-",
    amount: "Rs. 100/-",
    // paymentLink: "https://rzp.io/l/Karma-PES",
    redirectLink: "/events/mechanical/cadholic",
  },
];

export default GamesLists;
